config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root :to => "coding_skills#index"

  devise_for :users
  resources :coding_skills do
    resources :projects
  end

  resources :posts do
    resources :comments
  end

  resources :recommendations
end

app/models/coding_skill.rb
class CodingSkill < ActiveRecord::Base
  has_many :projects
  validates :name, :presence => true
end

app/controllers/coding_skills_controller.rb
class CodingSkillsController < ApplicationController
  def index
    @coding_skills = CodingSkill.all
    render :index
  end

  def show
    @coding_skill = CodingSkill.find(params[:id])
    render :show
  end

  def new
    @coding_skill = CodingSkill.new
  end

  def create
    @coding_skill = CodingSkill.new(coding_skill_params)
    if @coding_skill.save
      redirect_to coding_skills_path
    else
      render :new
    end
  end

  def edit
    @coding_skill = CodingSkill.find(params[:id])
    render :edit
  end

  def update
    @coding_skill = CodingSkill.find(params[:id])
    if @coding_skill.update(coding_skill_params)
      redirect_to coding_skills_path
    else
      render :edit
    end
  end

  def destroy
    @coding_skill = CodingSkill.find(params[:id])
    @coding_skill.destroy
    redirect_to coding_skills_path
  end





  private
  def coding_skill_params
    params.require(:coding_skill).permit(:name, :description)
  end
end

app/views/coding_skills/_form.html.erb
<%= render "layouts/errors", :object => @coding_skill %>

<%= form_for @coding_skill, remote: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/coding_skills/edit.html.erb
<h1>Edit Coding Skill</h1>

<%= render "form" %>

app/views/coding_skills/index.html.erb
<div id="main-photo">
  <div id="top_title_text">
    <h2>Welcome to the portfolio of Cody Bouscaren</h2>
  </div>
  <div id="bottom_title_text"
    <h1 > Web Developer </h1>
  </div>
</div>


<div class="container">
  <div id="welcome-box">
    <h1>Web Developer, Filmmaker, Problem Solver</h1>
      <p>Asymmetrical crucifix gastropub, <br>sartorial ennui iPhone Thundercats fingerstache party lomo craft<br>  beer sustainable.
         Quinoa fanny pack Helvetica Echo Park irony, hella ugh organic chillwave. <br>Synth photo booth +1 paleo Odd Future wolf tilde, beard shabby chic lumbersexual XOXO 8-bit crucifix PBR&B irony</p>
  </div>
</div>

  <div class="container">
    <div class="row first-row">
      <div class="col-sm-6 centered">
        <a href="https://github.com/chasereckling/cat_box">
        <img src="/assets/catbox.png" class="thumbnail-image"/>
        </a>
      </div>
      <div class="col-sm-6 centered">
        <a href="http://lit-woodland-6598.herokuapp.com/">
        <img src="/assets/calorie_counting.jpg" class="calories-image"/>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 centered thumbnail-div">
        <img src="/assets/thumbnail.jpeg" class="thumbnail-image"/>
      </div>
      <div class="col-sm-6 centered">
        <img src="/assets/calorie_counting.jpg" class="calories-image"/>
      </div>
    </div>
  </div>
</div>

app/views/coding_skills/new.html.erb
<div class="container">
<h1>New Coding Skill</h1>

<%= render "form" %>

</div>

app/views/coding_skills/show.html.erb
<h1><%= @coding_skill.name %></h1>



<% if @coding_skill.projects.any? %>
<h4>Here are the projects for <%= @coding_skill.name %> </h4>


<ul>
  <% @coding_skill.projects.each do |project| %>
    <li>
      <%= project.description %> |
      <%= link_to "Edit", edit_coding_skill_project_path(@coding_skill, project) %> |
      <%= link_to "Delete", coding_skill_project_path(@coding_skill, project),
                                          :data => {:confirm => "You sure, broski?",
                                          :method => "delete"} %> </p>

    </li>
    <% end %>
</ul>

<% else %>
<p>
  There are no projects for <%= @coding_skill.name %> just yet!
</p>

<% end %>

<p> <%= link_to "Add a project", new_coding_skill_project_path(@coding_skill) %></p>
<p><%= link_to "Delete Coding Skill", coding_skill_path(@coding_skill),
                                      :data => {"confirm" => "You sure, broski?",
                                      :method => "delete"} %></p>

<p> <%= link_to "Return to Homepage", coding_skills_path %></p>