config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root :to => "coding_skills#index"

  devise_for :users
  resources :coding_skills do
    resources :projects
  end

  resources :posts do
    resources :comments
  end

  resources :recommendations
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  validates :recommendation_content, :presence => true
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  def index
    @recommendations = Recommendation.all
  end

  def new
    @recommendation = Recommendation.new
  end

  def create
    @recommendation = Recommendation.new(recommendation_params)
    @recommendation.recommendation_author = current_user.email
    if @recommendation.save
      respond_to do |format|
        format.html { redirect_to coding_skills_url }
        format.js
      end
    end
  end

  def destroy
  end

  private
  def recommendation_params
    params.require(:recommendation).permit(:recommendation_content)
  end
end

app/views/recommendations/_best_of.html.erb
<div id="best_of">
  <h1>Recommendations for Cody Bouscaren</h1>

  <p>Add a recommendation below!</p>

    <% if current_user %>
    <%= link_to "Add a recommendation", new_recommendation_path, class: "btn btn-success", remote: true %>
    <% else %>
    <p><%= link_to "Sign in to add a recommendation", new_user_session_path %></p>
    <% end %>



  <h3>Recommendations</h3>
  <div id="recommendations">
    <% if @recommendations.any? %>
      <%= render(@recommendations) %>
    <% end %>
  </div>



  <%= link_to "Close", root_path, id: "hide_best_of", class: "btn btn-success" %>

  </div>

app/views/recommendations/_form.html.erb
<div id="recommendation-header">
  <h3>Hey there, <%= current_user.email %>!</h3>
</div>

<%= bootstrap_form_for @recommendation, remote: true do |f| %>
  <%= f.text_area :recommendation_content, label: "What do you like about Cody?" %>
  <%= f.submit "Add recommendation", class: "btn btn-success" %>
<% end %>

app/views/recommendations/_recommendation.html.erb
<p><%= recommendation.recommendation_content %> -<%= recommendation.recommendation_author %></p>

app/views/recommendations/create.js.erb
$('form').hide();
$('#new_recommendation_link').show();
$('#recommendation-header').hide();
$('#recommendations').append('<%= j render (@recommendation) %>');

app/views/recommendations/index.html.erb
<%= render "best_of" %>

app/views/recommendations/index.js.erb
$('#best_of_link').hide().after('<%= j render("best_of") %>');

app/views/recommendations/new.html.erb
<h1>Recommendation</h1>

<%= render "form" %>

app/views/recommendations/new.js.erb
$('#new_recommendation_link').hide().after('<%= j render("form") %>');