config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root :to => "coding_skills#index"

  devise_for :users
  resources :coding_skills do
    resources :projects
  end

  resources :posts do
    resources :comments
  end

  resources :recommendations
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :post_title, :presence => true
  validates :post_content, :presence => true

  has_attached_file :attached_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :attached_image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    if current_user.admin
      @post = Post.new
    else
      flash[:notice] = "You do not have admin privileges"
      redirect_to coding_skills_path
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post saved."
      redirect_to posts_path
    else
      flash[:notice] = "Please try again."
      render :new
    end
  end

  def edit
    if current_user.admin
      @post = Post.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post updated."
      redirect_to posts_path
    else
      flash[:notice] = "Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:post_title, :post_content, :attached_image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<div id="comments">
  <h4><%= link_to "Hide comments", posts_path, id: "hide_comments" %></h4>
  <% if @post.comments.any? %>
    <% if current_user && current_user.admin? %>
      <% @post.comments.each do |comment| %>
        <p><%= comment.comment_content %>  <strong>-<%= comment.comment_author %></strong><%= link_to "X", post_comment_path(@post, comment),
        :data => {:confirm => "Are you sure you want to delete this comment?",
        :method => "delete"} %></p>
      <% end %>
    <% else %>
        <% @post.comments.each do |comment| %>
          <p><%= comment.comment_content %>  <strong>-<%= comment.comment_author %></strong></p>
        <% end %>
    <% end %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="padding">
  <h1>Edit Blog Post</h1>

  <%= bootstrap_form_for @post do |f| %>
    <%= f.text_field :post_title %>
    <br><br>
    <%= f.text_area :post_content %>
    <br>
    <%= f.file_field :attached_image %>
    <br>
    <%= f.submit "Edit post", class: "btn btn-success" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div id="blog_photo">
</div>


  <div id="blog-index">
    <h1>Blog</h1>

    <% if current_user %>
      <%= link_to "New post", new_post_path %>
    <% end %>

    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div id="blog_<%= post.id %>" class="blog-title">
          <h3><%= link_to post.post_title, post_path(post) %></h3>
          <h4><%= post.created_at.time.strftime "%B %d, %Y" %></h4>

          <%= image_tag post.attached_image.url(:medium), id: "blog_pic" %>
          <p><%= post.post_content %></p>


          <h4>Comments: <%= post.comments.length %></h4>
          <h4><%= link_to "Show comments", post_path(post), id: "show_comments_link", remote: true   %></h4>
          <div class="show-comments">
          </div>
          <div id="allcomments"></div>
          <% if current_user %>
            <h4><%= link_to "Add a comment", new_post_comment_path(post), class: "new_comment_link", remote: true  %></h4>
          <% else %>
            <p><%= link_to "Sign in to post comments.", new_user_session_path %></p>
          <% end %>
          <br>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/posts/new.html.erb
<div class="padding">
  <h1>New Blog Post</h1>

  <%= bootstrap_form_for @post, :url => posts_path, :html => { :multipart => true} do |f| %>
    <%= f.text_field :post_title %>
    <br><br>
    <%= f.text_area :post_content %>
    <br>
    <%= f.file_field :attached_image %>
    <br>
    <%= f.submit "Add post", class: "btn btn-success" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="padding">
  <div id="blog-title">
    <h1><%= @post.post_title %></h1>
    <h4><%= @post.created_at.time.strftime "%B %d, %Y" %></h4>
  </div>
  <%= image_tag @post.attached_image.url(:medium), id: "blog-pic" %>
  <p><%= @post.post_content %></p>

  <h3>Comments</h3>

  <% if current_user %>
    <%= link_to "Add a comment", new_post_comment_path(@post), id: "new_comment_link", class: "btn btn-success", remote: true %>
  <% else %>
    <p><%= link_to "Sign in to post comments.", new_user_session_path %></p>
  <% end %>

  <div id="comments">
    <% if @post.comments.any? %>
      <% if current_user && current_user.admin? %>
        <% @post.comments.each do |comment| %>
          <p><%= comment.comment_content %>  <strong>-<%= comment.comment_author %></strong><%= link_to "X", post_comment_path(@post, comment),
          :data => {:confirm => "Are you sure you want to delete this comment?",
          :method => "delete"} %></p>
        <% end %>
      <% else %>
          <% @post.comments.each do |comment| %>
            <p><%= comment.comment_content %>  <strong>-<%= comment.comment_author %></strong></p>
          <% end %>
      <% end %>
    <% end %>
  </div>

  <% if current_user %>
    <% if current_user.admin %>
      <p><%= link_to "Edit post", edit_post_path %></p>
      <p><%= link_to "Delete post", post_path(@post), :data => {:confirm => "Are you sure you want to delete this post?",
      :method => "delete"} %></p>
    <% end %>
  <% end %>
</div>

app/views/posts/show.js.erb
$('#show_comments_link').hide();
$('#allcomments').html('<%= j render("comments") %>')